### PR TITLE
fix: modify pageWrapper margin style to keep top, bottom, left, and right equal

### PR DESCRIPTION
**Pull request by Aaron-zon**
## Proposed changes

修改pageWrapper边距样式保持上下左右边距相等
image

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Linked Issues

#21

### CODE REVIEW

**Comment by kirklin** [comment]
image

image

**Comment by kirklin** [comment]
image

**Comment by Aaron-zon** [comment]
image
image
image
@kirklin 这样看起来怎么样

**Comment by Aaron-zon** [comment]
右侧滚动的时候看起来不是圆角QAQ

**Comment by Aaron-zon** [comment]
@kirklin 这个样子可以吗
image
image

**Comment by kirklin** [comment]
LGTM

**Pull request merged**
